require("core.plugin_config.mason")
require("core.plugin_config.colorscheme")
require("core.plugin_config.lualine")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.vim-test")
require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.dap_config")
require 'alpha'.setup(require 'core.plugin_config.alpha_dashboard'.config)
require("core.plugin_config.hop")
require("core.plugin_config.nvim-colorizer")
require("core.plugin_config.goto-preview")
require("core.plugin_config.toggle-term")
require("core.plugin_config.indent-guide")
require("core.plugin_config.leap")
require("core.plugin_config.flit")
require("core.plugin_config.telescope-file-browser")
